name: sinSong
version: '1.0.1'
main: org.sinSong.SinSong
api-version: '1.21'
author: Sinsamuth

commands:
  sinsong:
    description: Main command for SinSong plugin
    usage: /sinsong <subcommand>
    permission: sinsong.use
    subcommands:
      reload:
        description: Reload the plugin configuration
        usage: /sinsong reload
        permission: sinsong.reload

  playsong:
    usage: /playsong <song_name>
    description: Play a song
    permission: sinsong.play

  stopsong:
    usage: /stopsong
    description: Stop the current song
    permission: sinsong.stop

  skipsong:
    usage: /skipsong
    description: Skip to the next song
    permission: sinsong.skip

  togglemusic:
    usage: /togglemusic
    description: Mute or unmute music
    permission: sinsong.togglemusic
